//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_User { get; set; }
        public string Name_User { get; set; }
        public string Firstname_User { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Age { get; set; }
        public int ID_Gender { get; set; }
        public int ID_Freetime { get; set; }
        public string Adout_user { get; set; }
        public int ID_fav_place { get; set; }
        public int ID_fav_kitchen { get; set; }
        public string Photo_user { get; set; }
    
        public virtual Freetime Freetime { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Kitchen Kitchen { get; set; }
        public virtual Place Place { get; set; }
    }
}
